version: 2
jobs:
  build:
    docker:
      - image: simonsdave/xenial-dev-env:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            source cfg4dev
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            nosetests
      - store_artifacts:
          path: test-reports
          destination: test-reports
