version: 2
jobs:
  build:
    docker:
      - image: simonsdave/xenial-dev-env:latest
        environment:
          DOCKER_TEMP_IMAGE=simonsdave/cloudfeaster:bindle
    working_directory: ~/repo
    steps:
      - checkout
      - run: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run: pip install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: pip check
      - run: flake8
      - run: shellcheck $(find . -name \*.sh)
      - run: git log -p | scanrepo
      - run: nosetests --with-coverage --cover-branches --cover-erase --cover-package dev_env_testing
      - run: python setup.py bdist_wheel sdist --formats=gztar
      - run: ls -laR
      - setup_remote_docker:
      - run: docker images
      - run: dockerfiles/build-docker-image.sh "$PWD/dist/dev_env_testing-$(current-python-version.sh).tar.gz" "$DOCKER_TEMP_IMAGE"
      - run: docker images
