version: 2
jobs:
  build:
    docker:
      - image: simonsdave/xenial-dev-env:latest
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run: pip install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: pip check
      - run: flake8
      - run: git log -p | scanrepo
      - run: python setup.py bdist_wheel sdist --formats=gztar
      - run: nosetests --with-coverage --cover-branches --cover-erase --cover-package dev_env_testing
      - setup_remote_docker:
      - run: docker --version
      - run: docker run --rm ubuntu:16.04 /bin/bash -c "echo 'hi'"
