version: 2

_defaults: &defaults
  working_directory: ~/repo
  docker:
  - image: simonsdave/xenial-dev-env:latest
  environment:
    DOCKER_TEMP_IMAGE=simonsdave/dev-env-testing:bindle

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run: pip install --requirement requirements.txt
      - save_cache:
          paths:
            - ./env
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run: pip check
      - run: flake8
      - run: shellcheck $(find . -name \*.sh)
      - run: git log -p | scanrepo
      - run: nosetests --with-coverage --cover-branches --cover-erase --cover-package dev_env_testing
      - run: python setup.py bdist_wheel sdist --formats=gztar
      - setup_remote_docker:
      - run:
          command: |
            CURRENT_VERSION=$(grep __version__ "$PWD/dev_env_testing/__init__.py" | sed -e "s|^.*=[[:space:]]*['\"]||g" | sed -e "s|['\"].*$||g")
            dockerfiles/build-docker-image.sh "$PWD/dist/dev_env_testing-$CURRENT_VERSION.tar.gz" "$DOCKER_TEMP_IMAGE"
      - deploy:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo 'deploy latest'
            fi
            if [[ "${CIRCLE_BRANCH}" =~ ^release\-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo 'deploy release'
            fi

#  deploy:
#    <<: *defaults
#
#    steps:
#      - run: docker images

# workflows:
#   version: 2
#   build_and_deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build
#           filters:
#             branches:
#               only:
#                 - master
#                 - /^release-.*$/
